// create an icon list that exist in the images/icons
part of '../scene_lib.dart';

List<String> iconList = [
  'airpurifer0',
  'airpurifer100',
  'alarm_partial',
  'alarm_red',
  'alarm_siren_gray0',
  'alarm_siren_gray100',
  'alarm_siren_red0',
  'alarm_siren_red100',
  'alarm0',
  'audio0',
  'audio100',
  'barrierClosing',
  'barrierOpening',
  'brama_2-50',
  'brama50',
  'com.fibaro.rainSensor',
  'com.fibaro.rainSensor0',
  'com.fibaro.windSensor',
  'czajnik0',
  'czajnik100',
  'czujnik_ruchu0',
  'czujnik_ruchu100',
  'czujnik_zalania0',
  'czujnik_zalania100',
  'dehumidifier0',
  'dehumidifier100',
  'door_lock100',
  'doorbell_dark0',
  'doorbell_dark100',
  'drzwi0',
  'drzwi100',
  'energy_meter',
  'evening',
  'garageDoor_sectionalClosing',
  'garageDoor_sectionalOpening',
  'gate_doubleLeafClosing',
  'gate_doubleLeafOpening',
  'humidifier0',
  'humidifier100',
  'klimatyzator0',
  'klimatyzator100',
  // 'lampaogrodowa0',
  // 'lampaogrodowa100',
  'light0',
  'light100',
  'morning',
  'onoff0',
  // 'onoff100',
  'preasure_sensor',
  // 'roleta_wewo',
  'roleta_wew100',
  'scene_auto',
  'scene_block',
  'scene_dinner',
  'scene_dinner2',
  'scene_entrance',
  'scene_entrance2',
  'scene_exit',
  'scene_exit2',
  'scene_lua',
  'scene_magic',
  'scene_movie',
  'scene',
  'smoke_sensor0',
  'smoke_sensor100',
  'wiatrak0',
  'wiatrak100',
];
